### ISSUE TITLE
Return elapsed time on record

### ISSUE THREAD

**Issue by kqosh** [toefel18/patan#12]
```java
DurationStore#void recordElapsedTime(String name, Stopwatch stopwatch); //should return stopwatch.elapsedMillis() instead of void.
```

**Comment by toefel18** [comment]
scheduled for RC2.  API change does not break clients but affects implementations. There aren't any implementations yet and the API of version 1 is not considered stable until 1.0.0 has a final release.

**Comment by toefel18** [comment]
Fixed!  available in RC2 https://jcenter.bintray.com/nl/toefel/patan/
